name: Docker Image CI

on: [pull_request]
jobs:

  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    
    - name: Verify
      env: 
        API_HEADER: "Accept: application/vnd.github.v3+json; application/vnd.github.antiope-preview+json"
        AUTH_HEADER: "Authorization: token ${{ secrets.GITHUB_TOKEN }}"
        URI: https://api.github.com
      run: |
        curl -sSL -H $AUTH_HEADER -H $API_HEADER -d '{"body":"Test comment"}' -H "Content-Type: application/json" -X POST "$URI/repos/${{ github.repository }}/issues/${{ github.number }}/comments"
        
      
